### ISSUE TITLE
[Feature Request] Add ability to unlike if liked + add "I don't like this song" shorcut

### ISSUE THREAD

**Issue by karimawii** [yeti2006/SpotiLike#1]
Hey, I really love your extension, it's really useful and I'll appreciate it so much if you looked into my request. 
1. Add the ability to use the shortcut key again to unlike a song if it's liked so, [check the saved songs for the current song](https://developer.spotify.com/documentation/web-api/reference/#/operations/check-users-saved-tracks) then [delete track from saved songs](https://developer.spotify.com/documentation/web-api/reference/#/operations/remove-tracks-user)

2. I don't know if this is possible using the API or not because I searched for it but I didn't find an Endpoint for it but, I use Release Radar and Discover Weekly a lot and I use the "I don't like this song" button when I'm discovering new songs in those playlists so, if possible can you add it?
Button:
![image](https://user-images.githubusercontent.com/69881381/162597219-282ef207-996a-4b3e-bbc9-9011558d7f0e.png)

**Comment by karimawii** [comment]
Maybe this?
https://developer.spotify.com/documentation/web-api/reference/#/operations/remove-tracks-playlist

**Comment by yeti2006** [comment]
Hello! I pushed some code to add the first feature request you mentioned.
> 1. Add the ability to use the shortcut key again to unlike a song if it's liked so, [check the saved songs for the current song](https://developer.spotify.com/documentation/web-api/reference/#/operations/check-users-saved-tracks) then [delete track from saved songs](https://developer.spotify.com/documentation/web-api/reference/#/operations/remove-tracks-user)

Basically, if you re-use the shortcut on a already liked song, then it is gonna unlike the song(Remove from your Liked Songs library) and I hope that's what you requested.

For the second request, I didn't find any endpoint either, but I'll keep looking for a possible solution and update the app if I find any.

I haven't setup an auto-update system inside the app itself. I won't be able to compile a Windows standalone executable for now since I don't have a Windows machine with me currently, the updated code is in the repo so you can either manually freeze it or run it from source.
